Added default value in variable.tf
spotinst/terraform-spotinst-ocean-aks-np-k8s pull request #12
Opened 2023-09-04 10:16 UTC by sharadkesarwani

Added default value in variable.tf to avoid asking value for option field value in case of terraform apply.

# Jira Ticket
Ref: https://spotinst.atlassian.net/browse/SPOTAUT-16289

2023-09-05 11:02 UTC, chandra1-n commented on variables.tf
> +  default     = false
change it to null for bool type also

2023-09-05 11:02 UTC, chandra1-n commented on variables.tf
> +  default     = false
change it to null for bool type also

2023-09-05 11:03 UTC, chandra1-n requested changes
please fix review comments

2023-09-05 11:32 UTC, sharadkesarwani commented on variables.tf
> +  default     = false
Gave null as default value

2023-09-05 11:33 UTC, sharadkesarwani commented on variables.tf
> +  default     = false
Gave null as default value

2023-09-06 05:05 UTC, chandra1-n approved these changes

2023-09-06 05:05 UTC, merged